### PR TITLE
Modularity

### PR DESCRIPTION
**Pull request by alive-zk**

### CODE REVIEW

**Comment by alive-zk** [comment]
@jbenet, @tenedor can haz CR on last three commits?

**Comment by jbenet** [comment]
@ali01 done CR. all LGTM.

**Comment by alive-zk** [comment]
@jbenet, thx for the CR!

**Comment by alive-zk** [comment]
@jbenet, @tenedor, when you get a chance, please code review the last two commits.

Per a conversation with @jbenet, the second commit will soon be improved on (after the end of our current sprint to an MVP) with a stateful proxy abstraction.

**Comment by alive-zk** [comment]
@jbenet, @tenedor, can haz code review for two commits above?

**Comment by alive-zk** [comment]
@tenedor: I can haz CR for 5 commits above?

**Comment by tenedor** [comment]
# very small details, otherwise all LGTM

**Comment by alive-zk** [comment]
@tenedor, can haz CR on last two fixups?

**Comment by tenedor** [comment]
# MERGE READY!

**Pull request merged**
