### PR TITLE
Sources

### PR DESCRIPTION
**Pull request by tenedor**
Creates a frontend Sources view accessible via a button in Acorn Controls. Missing:
- complimentary shell.sources() method on backend
- icon for Sources button

### CODE REVIEW

**Comment by tenedor** [comment]
# @ali01 @jbenet Ready for CR

**Comment by alive-zk** [comment]
windham: per in person conversation, let me know when this is ready for CR

**Comment by tenedor** [comment]
@ali01 fixed up initialization and rendering methods, ready for CR now

I also un-commented out `sources = this.shell.sources()`, so before merging this in either yours should get merged in or a fixup should return the commenting out and `TODO` message

**Comment by alive-zk** [comment]
# MERGE READY

Actually, could you comment out the `sources = this.shell.sources()` line so that this can be merged now?
I'll uncomment it as soon as the code restructuring is pushed.

**Comment by tenedor** [comment]
# MERGED

**Pull request closed without merging**
